# Site settings
# in the templates available like {{ site.myvariable }}.
title: Lingyu Li, VR Developer.
email: lingyu.li@rutgers.edu
brand: Luke217
headline: Intuitive VR developer
description: > # this means to ignore newlines until "baseurl:"
   Lingyu Li's Portfolio
baseurl: "/" # the subpath of your site, e.g. /blog
url: "lingyuli.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: lingyu.li@rutgers.edu
phone: +1-732-485-4313

# Tracking
googleAnalitycsID: UA-83933844-1

